### ISSUE TITLE
Cannot install smtplib

### ISSUE THREAD

**Issue by aminvakil** [mrwn007/M3M0#1]
Both python 2 and python3 gives me this error.
Steps to reproudce:
```
virtualenv venv --python=/usr/bin/python3
source venv/bin/activate
pip install -r requirements.txt
....
  ERROR: Could not find a version that satisfies the requirement smtplib (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for smtplib (from -r requirements.txt (line 4))
python -V
Python 2.7.16
```
```
virtualenv venv --python=/usr/bin/python2
source venv/bin/activate
pip install -r requirements.txt
....
  ERROR: Could not find a version that satisfies the requirement smtplib (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for smtplib (from -r requirements.txt (line 4))
python -V
Python 3.7.4
```

**Comment by LuongPhuHoa** [comment]
got the same error

**Comment by mrwn007** [comment]
try to install it manual

**Comment by aminvakil** [comment]
doesn't make any difference
```
[aminvakil@aminvakil ~]$ cd /tmp
[aminvakil@aminvakil tmp]$ git clone https://github.com/mrwn007/M3M0
Cloning into 'M3M0'...
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 183 (delta 34), reused 0 (delta 0), pack-reused 105
Receiving objects: 100% (183/183), 8.82 MiB | 1.77 MiB/s, done.
Resolving deltas: 100% (55/55), done.
[aminvakil@aminvakil tmp]$ cd M3M0/
[aminvakil@aminvakil M3M0]$ virtualenv venv
Using base prefix '/usr'
New python executable in /tmp/M3M0/venv/bin/python
Installing setuptools, pip, wheel...
done.
[aminvakil@aminvakil M3M0]$ source venv/bin/activate
(venv) [aminvakil@aminvakil M3M0]$ python -V
Python 3.7.4
(venv) [aminvakil@aminvakil M3M0]$ pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting colorama (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting termcolor (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting smtplib (from -r requirements.txt (line 4))
  ERROR: Could not find a version that satisfies the requirement smtplib (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for smtplib (from -r requirements.txt (line 4))
(venv) [aminvakil@aminvakil M3M0]$ pip install smtplib
Collecting smtplib
  ERROR: Could not find a version that satisfies the requirement smtplib (from versions: none)
ERROR: No matching distribution found for smtplib
```

**Comment by mrwn007** [comment]
First, the real environment manager is conda, and anaconda is actually a collection of generally used packages for scientific calculation, so it is not necessary for creating an environment.

Second, smtplib is a built-in package for both python2.7 and python3.x, so there is no need for installation. You can import it without installing any other package.

Finally, what source activate <venv name> real does is that modify your environment variables in the current console. That also means change the path of command python and pip and the path where python program looks for installed modules. In a word, source activate <venv name> activate a separated environment for python.

**Comment by aminvakil** [comment]
> First, the real environment manager is conda, and anaconda is actually a collection of generally used packages for scientific calculation, so it is not necessary for creating an environment.
> 
I don't want these repo requirements conflicts with my whole system python packages, therefore it's necessary and shouldn't be a problem to create a virtual environment and install packages inside it.
> Second, smtplib is a built-in package for both python2.7 and python3.x, so there is no need for installation. You can import it without installing any other package.
> 
Then I have to ask why smtplib is in requirements.txt if it isn't needed?
> Finally, what source activate real does is that modify your environment variables in the current console. That also means change the path of command python and pip and the path where python program looks for installed modules. In a word, source activate activate a separated environment for python.

That's exactly what I want, to use python and pip of virtual environment and install extra packages in virtual environment as well.
