### ISSUE TITLE
doubts 

### ISSUE THREAD

**Issue by F4kda7** [mrwn007/M3M0#3]
hello , 

i was playing around with this tool

but i have a doubt

i don't know clearly what to do when the tool shows this:

i tried to add the target link and i put a text file with the sites ( joomla.txt)

but it doesn't work..
                  
choice Number => 7

Go to Tools/tool7 
 
Put Ur  List like this : http://www.site.com/administrator/index.php&user&~password#
                             y = yes 
                             n = no
~>y

  __  __                   _           _   _       _                 _ 
 |  \/  | __ _ ___ ___    | |_ __ ___ | | | |_ __ | | ___   __ _  __| |
 | |\/| |/ _` / __/ __|_  | | '_ ` _ \| | | | '_ \| |/ _ \ / _` |/ _` |
 | |  | | (_| \__ \__ \ |_| | | | | | | |_| | |_) | | (_) | (_| | (_| |
 |_|  |_|\__,_|___/___/\___/|_| |_| |_|\___/| .__/|_|\___/ \__,_|\__,_|
                                            |_|                        
Note : http://www.site.com/administrator/index.php&user&~password#							  
                                                          

Enter List name :http://www.my_target.com/administrator/index.php&admin&password
Traceback (most recent call last):
  File "shelljm.py", line 181, in <module>
    ListStie = open(spy, 'r').readlines()      
IOError: [Errno 2] No such file or directory: 'http://www.my_target.com/administrator/index.php&admin&password
unknown error :| 

sorry for the inconvenience

thanks

**Comment by F4kda7** [comment]
Installation method github
Operating system: Parrot GNU/Linux 4.8
Python version: i have both installed but i was using python 2.7.17 at this moment
kernel Linux 5.4.0-3parrot1-amd64
the system is udpated

**Comment by XxHailHydraxX** [comment]
your trying to import http://www.my_target.com/administrator/index.php&admin&password saying its a txt Document...

->Enter List name :http://www.my_target.com/administrator/index.php&admin&password 
-->Enter List Name:links.txt ( or what ever you want to name it 
you must add the links to txt file....

**Comment by XxHailHydraxX** [comment]
(1) python Start.py
(2) Press 7
(3) Y
(4) Enter YOUR TXT file that has your urls in it ( inside Tool7 Folder)
(5) Enter
(6)Success
